project:
  alias: expeditor-acceptance
  base_config:
    repo: chef-boneyard/expeditor-acceptance
    file: .expeditor/base_config.yml

pipelines:
  - new_cd_public:
      definition: .expeditor/new-cd-pipeline.pipeline.yml
      public: true
  # - new_cd_private:
  #     definition: .expeditor/new-cd-pipeline.pipeline.yml
  #     env:
  #       - EXPEDITOR_CHANNEL: acceptance
  - omnibus/harmony-acceptance:
      canary: true
      env:
        - VAULT_ADDR: "https://vault-acceptance.chef.co:8200"
  - habitat/build:
      canary: true
      env:
        - VAULT_ADDR: "https://vault-acceptance.chef.co:8200"

promote:
  channels:
    - dummy

merge_actions:
  - built_in:bump_version:
      ignore_labels:
        - "Version: Skip Bump"
  - bash:.expeditor/update_version.sh:
      only_if: built_in:bump_version
  - built_in:update_changelog:
      ignore_labels:
        - "Changelog: Skip Update"
  - trigger_pipeline:habitat/build
  # - trigger_pipeline:omnibus/harmony-acceptance

subscriptions:
  - workload: generic_workload_published:acceptance_tests:*
    actions:
      - bash:.expeditor/trigger_pr_merge_tests.sh
  - workload: buildkite_hab_build_group_published:{{agent_id}}:*
    actions:
      - built_in:promote_habitat_packages
  # github_release_published does not exist yet
  #
  # - workload: github_release_published:*
  #   actions:
  #     - bash:.expeditor/trigger_release_test.sh

